home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="home"),
]

inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'

urlpatterns = [
    path("stock/", views.total_stock_list, name="total_stock_list"),

    path("flow/", views.inventory_flow, name="inventory_flow"),
    path("add-stock/", views.add_stock_view, name='add_stock'),
    path("flow/delete/<int:pk>/", views.delete_flow_view, name='delete_flow'),
]

saas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),

    path('', include('home.urls')),

    path('inventory/', include('inventory.urls')),

    path('services/', include('services.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path("", views.total_services_list, name="services_list"),
    path("create/", views.create_service, name='create_service'),
    path("update/<int:pk>/", views.update_service, name='update_service'),
    path("delete/<int:pk>/", views.delete_service, name='delete_service'),
    path("details/<int:pk>/", views.get_service_details, name='get_service_details'),path("delete/<int:pk>/", views.delete_service, name='delete_service'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    return render(request, 'home/home.html')

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}MSS - Início{% endblock %}
{% load static %}


{% block content %}
<div class="d-flex flex-column">
    <div class="px-4 pt-5 text-center">
        <h1 class="display-5 fw-bold text-body-emphasis">Sistema de Gerenciamento MSS</h1>
    </div>

<div class="container px-4 pb-5 pt-4" id="custom-cards">
    <div class="row row-cols-1 row-cols-lg-2 row-cols-xl-4 align-items-stretch g-4 py-3">
        
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{% static 'images/estoque.jpg' %}'); background-size: cover; background-position: center;">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1" style="background-color: rgba(0, 0, 0, 0.5);">
                    <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Estoque Total</h3>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                            <i class="bi bi-boxes fs-2"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <a href="{% url 'inventory:total_stock_list' %}" class="btn btn-outline-light">Consultar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{% static 'images/fluxo.jpg' %}'); background-size: cover; background-position: center;">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1" style="background-color: rgba(0, 0, 0, 0.5);">
                    <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Fluxo de Estoque</h3>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                            <i class="bi bi-arrow-left-right fs-2"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <a href="{% url 'inventory:inventory_flow' %}" class="btn btn-outline-light">Registrar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{% static 'images/marcacao.jpg' %}'); background-size: cover; background-position: center;">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1" style="background-color: rgba(0, 0, 0, 0.5);">
                    <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Marcações</h3>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                            <i class="bi bi-card-checklist fs-2"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <a href="{% url 'services:services_list' %}" class="btn btn-outline-light">Acessar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="col">
            <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{% static 'images/financeiro.webp' %}'); background-size: cover; background-position: center;">
                <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1" style="background-color: rgba(0, 0, 0, 0.5);">
                    <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">Gestão de Cobranças</h3>
                    <ul class="d-flex list-unstyled mt-auto">
                        <li class="me-auto">
                            <i class="bi bi-cash-coin fs-2"></i>
                        </li>
                        <li class="d-flex align-items-center">
                            <a href="#" class="btn btn-outline-light">Ver Cobranças</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        

    </div>
</div>
</div>
{% endblock %}